title = "Kent Barrett Art"
baseURL = "https://kentbarr.github.io/KBA/"
languageCode = "en-us"
theme = "airspace"
publishDir = "docs"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "Artwork"
      url = "work"
    [[menu.header]]
      weight = 2
      name = "Articles"
      url = "articles"
    [[menu.header]]
      weight = 3
      name = "Blog"
      url = "blog"
    [[menu.header]]
      weight = 4
      name = "Service"
      url = "service"
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "contact"

    [[menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "contact"
    [[menu.footer]]
      weight = 3
      name = "How it works"
      url = "work"
    [[menu.footer]]
      weight = 4
      name = "Blog"
      url = "blog"
    [[menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"

  [params.slider]
    enable = true
    title = "Photographic Art <br>&amp; Law &amp; Stuff "
    subtitle = "The phography and artwork of Kent Barrett, plus articles about law and money by various authors."
    bgImage = "img/slider-bg.jpg"
    btnText = "Discover Our Projects"
    url = "#"

  [params.wrapper]
    enable = true
    image = "img/wrapper-img.png"
    title = "About Me"
    italic = "They tell me I'm from Manitoba. But then, they could have told me anything."
    paragraph = "I composed and shot my first photograph before I could talk. I took it with a Kodak Brownie Hawkeye which, because of the primitive optics, presents the image with left and right reversed as in a mirror. This was maddening to a toddler. Not only that, once I had managed to fiddle that out, I very carefully composed the shot so my parents' heads were cleanly in the frame. Then the photos came back from the drugstore and the very tops of Dad's head was cut off. Since that day I have hated all camera viewfinders *except* SLR's that show exactly 100% of the frame. ALL of them, even Leicas which are of course very impressive and beautiful machines. But fuck 'em. Because paralax."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    bgImage = "img/feature-bg.jpg"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
    [params.call.button]
      url = "#"
      text = "tell us your story"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
